name: powermode-scan

on:
  pull_request:
    branches:
      - release

jobs:
  powermode-scan:
    runs-on: ubuntu-latest
    
    steps:
      # Checking out commit before used in generating diff file.
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: powermode-scan-pull-request
        uses: ncino/powermode-scan@v1
        with:
          pmd-version: '6.33.0'
          rulesets: '$GITHUB_WORKSPACE/.github/workflows/apexAndVisualForceRuleset.xml'
          differential-scan: 'false'
          failOnViolation: 'false'
          dir: '$GITHUB_WORKSPACE'

