name: Bump version

on:
  push:
    branches:
      - release

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.2.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: release

  actions-tagger:
    needs: bump-version
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
          