name: Packaging new merges to release

on:
  push:
    branches: [ release ]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
